module.exports = {
    truths: [
      "What's your biggest fear?",
      "What's a secret you've never told anyone?",
      "Who was your first crush?",
      "What's the most embarrassing thing you've ever done?",
      "What's something you wish you could change about yourself?",
      "What's the weirdest dream you've ever had?",
      "What's the most trouble you've ever been in?",
      "If you could trade lives with someone for a day, who would it be?",
      "What's your most irrational phobia?",
      "What's the most childish thing you still do?",
      "What's the longest you've gone without showering?",
      "What's your guilty pleasure TV show or movie?",
      "What's the most embarrassing item in your room right now?",
      "What's the worst gift you've ever received?",
      "What's the most spontaneous thing you've ever done?",
      "Who in this group would you least like to be stranded on a desert island with?",
      "What's the weirdest food combination you secretly enjoy?",
      "What's something you've done that you hope your parents never find out about?",
      "What's your most embarrassing childhood memory?",
      "What app on your phone do you waste the most time on?",
      "What's the most embarrassing thing in your search history?",
      "If you had to date someone in this group, who would it be?",
      "What's the worst lie you've ever told?",
      "What's your biggest pet peeve?",
      "What's the most embarrassing song on your playlist?",
      "What's something about yourself that sounds like a lie but is true?",
      "If you could only eat one food for the rest of your life, what would it be?",
      "What's the most expensive thing you've broken?",
      "What's the most awkward date you've been on?",
      "What's something you hope your future self doesn't do?",
      "What's your worst habit?",
      "What's the most embarrassing nickname you've ever had?",
      "What's something you did as a kid that you still feel guilty about?",
      "What's one thing you'd change about your appearance if you could?",
      "What's the most desperate thing you've done when you were hungry?",
      "What's something you're secretly proud of?",
      "What's a weird talent you have?",
      "What's the longest you've gone without sleeping?",
      "What's the most embarrassing thing you've posted online?",
      "If you had to get a tattoo right now, what would it be?",
      "What's the last thing you searched for online?",
      "What's a belief you had as a child that you now find ridiculous?",
      "What's the most embarrassing thing that's happened to you at school or work?",
      "If you could travel back in time, what's one thing you'd change?",
      "What's the luckiest thing that's happened to you?",
      "Who here do you secretly admire and why?",
      "What's the worst advice you've ever given?",
      "What conspiracy theory do you secretly believe might be true?",
      "If you could read anyone's mind, whose would it be?",
      "What's a lie you've told that got way out of hand?"
    ],
    dares: [
      "Do 10 jumping jacks!",
      "Say the alphabet backwards.",
      "Send a funny meme in the chat.",
      "Imitate another player until someone guesses who it is.",
      "Post an embarrassing photo (if you want!)",
      "Speak in an accent for the next three rounds.",
      "Let another player send a text message from your phone.",
      "Call a random contact and sing them Happy Birthday.",
      "Do your best impression of a celebrity.",
      "Show the most embarrassing photo on your phone.",
      "Let the group choose your profile picture for a day.",
      "Do a silly dance for 30 seconds.",
      "Tell a joke that will make everyone groan.",
      "Try to lick your elbow.",
      "Let someone style your hair however they want.",
      "Tell an embarrassing story about yourself.",
      "Speak without showing your teeth for the next three turns.",
      "Do your best impression of someone in the room.",
      "Let the group go through your phone for 30 seconds.",
      "Call a restaurant and ask if they deliver to the moon.",
      "Try to breakdance for 30 seconds.",
      "Wear your clothes backwards for the rest of the game.",
      "Act like a cat until your next turn.",
      "Do 20 squats right now.",
      "Let someone draw something on your face.",
      "Try to do a handstand against the wall.",
      "Speak in rhymes for the next three turns.",
      "Let the group choose a new hairstyle for you that you have to keep for the rest of the game.",
      "Post a status update on social media that the group decides.",
      "Do the worm (or attempt to).",
      "Talk to a household object like it's your crush for 30 seconds.",
      "Try to juggle with three items of the group's choosing.",
      "Wear your socks on your hands for the next three rounds.",
      "Make up a 30-second commercial for a toilet brush.",
      "Fill your mouth with water and try to whistle.",
      "Do your best robot dance.",
      "Try to balance three random objects on your head for 30 seconds.",
      "Let someone blindfold you and feed you something.",
      "Make a fashion item out of toilet paper and wear it.",
      "Switch clothes with the person to your left until your next turn.",
      "Make up a rap about someone in the room.",
      "Let the group give you a new nickname that you must respond to for the rest of the game.",
      "Talk like a news reporter for the next three turns.",
      "Use only gestures to communicate until your next turn.",
      "Do your best impression of someone's laugh in the room.",
      "Pretend to be a food critic and review the imaginary meal in front of you.",
      "Try to fit as many marshmallows (or other small food) in your mouth as possible.",
      "Call the 3rd contact in your phone and sing the chorus of your favorite song.",
      "Do a catwalk across the room like you're on a fashion runway.",
      "Let someone else apply makeup to you (if applicable)."
    ]
};
